name: Build IPA without signing 5 [FIX 2]
on:
  push:
    branches:
      - main # Change to your desired branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '5.1.1'

    - name: Build IPA
      run: |
        xcodebuild archive -workspace "raspberry.xcodeproj/project.xcworkspace/" -scheme raspberry -archivePath "build/YourProject.xcarchive" -configuration Release
        xcodebuild -exportArchive -archivePath "build/YourProject.xcarchive" -exportPath "build" -exportOptionsPlist "ExportOptions.plist"

    - name: Copy IPA to artifacts
      run: |
        mv "build/YourProject.ipa" "YourProject.ipa"

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v2
      with:
        name: YourProject-ipa
        path: YourProject.ipa
