name: Build IPA without signing 5 [FIX 5]
on:
  push:
    branches:
      - main # Change to your desired branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download and Unpack SDK
      run: |
        # Download the SDK .zip file
        curl -L -o sdk.zip "https://github.com/GrowtopiaJaw/iPhoneOS-SDK/releases/download/v1.0/iPhoneOS6.0.sdk.zip"
        # Unzip the SDK .zip file to the 'SDKs' directory
        mkdir SDKs
        unzip sdk.zip -d SDKs
        # Set the environment variable to the SDK folder path
        echo "SDK_PATH=$(pwd)/SDKs/iPhoneOS6.0.sdk" >> $GITHUB_ENV
    - name: Get SDK Path
      run: |
        echo "SHOWING SDK PATH"
        xcrun --show-sdk-path
        
    - name: pwd and ls
      run: |
       ls -l
       echo "------------------"
       pwd
   
    - name: Build IPA
      run: |
        xcodebuild archive -workspace "raspberry.xcodeproj/project.xcworkspace" -scheme raspberry -archivePath "build/YourProject.xcarchive" -configuration Release
        xcodebuild -exportArchive -archivePath "build/YourProject.xcarchive" -exportPath "build" -exportOptionsPlist "ExportOptions.plist"

    - name: Copy IPA to artifacts
      run: |
        mv "build/YourProject.ipa" "YourProject.ipa"

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v2
      with:
        name: YourProject-ipa
        path: YourProject.ipa
